# Site settings
title: Coding code
description: >
  A blog about coding
url: "http://codingcode.io" # the base hostname & protocol of the site
baseurl: "" # the subpath of your site, e.g. /blog/
site_repository: "https://github.com/odarriba/codingcode.io"

author: Óscar de Arriba
email: odarriba@gmail.com

social:
  twitter_username: odarriba
  github_username: odarriba
  facebook_username: odarriba
  youtube_username: odarriba
  linkedin_username: oscardearriba

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: "blog/page:num/"

# Separator to cut down the posts on index page
excerpt_separator: "<!--more-->"