# Site settings
title: Coding code
description: Another blog about coding
url: "http://codingcode.io" # the base hostname & protocol of the site
baseurl: "" # the subpath of your site, e.g. /blog/
site_repository: "https://github.com/odarriba/codingcode.io"

# Authors data
authors: 
  odarriba:
    name: "Óscar de Arriba"
    description: "Telecommunications engineer in love with web technologies."
    image: /assets/authors/odarriba.png
    twitter_username: "odarriba"
    github_username: odarriba
    linkedin_username: "oscardearriba"

# Main author (for the footer)
author: "Óscar de Arriba"
email: "odarriba@gmail.com"

# Social of the footer
social:
  twitter_username: odarriba
  github_username: odarriba
  # facebook_username:
  # youtube_username:
  linkedin_username: oscardearriba

# Disqus comments
disqus_shortname: coding-code

# Analytics track code
google_analytics: UA-60202861-1

# Build settings
markdown: kramdown

# Exclude readme
exclude:
 - README.md

# Pagination
paginate: 5
paginate_path: "page:num/"

# Separator to cut down the posts on index page
excerpt_separator: "<!--more-->"
# Permalinks of the site
permalink: /:year/:month/:day/:title.html

# Add sitemap gem
gems:
  - jekyll-sitemap